name: capitolis-assignment
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.25.1
  - beautifulsoup4=4.9.3
  - psycopg2=2.8.4
  - apscheduler=3.7.0
  - pip=19.3.1
  - pip:
    - python-dotenv==0.17.1
